global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: orders
    metrics_path: /metrics
    static_configs:
      - targets: ["orders:8081"]

  - job_name: payments
    metrics_path: /metrics
    static_configs:
      - targets: ["payments:8082"]

  - job_name: stock
    metrics_path: /metrics
    static_configs:
      - targets: ["stock:8083"]
